--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/MaskAbilities
build-by-default: true
branches:
- PM5
projects:
  MaskAbilities:
    path: ""
    libs:
       - src: muqsit/InvMenu/InvMenu
         version: ^4.6.5
         branch: "pm5"
    lint:
      phpstan: false
...
